### ISSUE TITLE
How to manually specify the number of replicas?

### ISSUE THREAD

**Issue by authwork** [hydro-project/anna#35]
@vsreekanti 
Hello, there are four parameters when setting the replication
```
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1
```
I guess ```memory``` means how many replicas are stored in memory and ```ebs``` means how many replicas are stored in disk. How about ```minimum``` and ```local```?
If I want to run a cluster of 12 anna nodes with each key has 8 replicas in memory-only mode, how to set these parameters?

My current setting likes:
```
replication:
  memory: 8
  ebs: 0
  minimum: 8
  local: 1
```
My concern is 12*1(local) > 8(memory), it seems not right.

Many thanks

Update: When I run Anna (local mode) with the following configuration, the client works fine.
I only runs route and server.
```
./build/target/kvs/anna-route &
./build/target/kvs/anna-kvs &
```
```
monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring:
      - 127.0.0.1
  ip: 10.1.2.66
user:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
  ip: 10.1.2.66
server:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
  seed_ip: 10.1.2.66
  public_ip: 10.1.2.66
  private_ip: 10.4.2.2
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
ebs: ./
capacities: # in GB
  memory-cap: 1
  ebs-cap: 0
threads:
  memory: 1
  ebs: 1
  routing: 1
  benchmark: 1
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1
```

**Comment by authwork** [comment]
My configuration file:
```
monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring:
      - 127.0.0.1
  ip: 10.1.2.69 // each node's ip
user:
  monitoring:
      - 127.0.0.1
  routing: 
      - 10.1.2.66
      - 10.1.2.67
      - 10.1.2.68
      - 10.1.2.69
      - 10.1.2.70
      - 10.1.2.71
      - 10.1.2.72
      - 10.1.2.73
  ip: 10.1.2.69 // each node's ip
server:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
      - 10.1.2.67
      - 10.1.2.68
      - 10.1.2.69
      - 10.1.2.70
      - 10.1.2.71
      - 10.1.2.72
      - 10.1.2.73
  seed_ip: 10.1.2.66
  public_ip: 10.1.2.69 // each node's public ip
  private_ip: 10.4.2.5 // each node's private ip
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
ebs: ./
capacities: # in GB
  memory-cap: 1
  ebs-cap: 0
threads:
  memory: 1
  ebs: 1
  routing: 1
  benchmark: 1
replication:
  memory: 8
  ebs: 0
  minimum: 8
  local: 1
```

The output:
```
kvs> PUT b 1.0
Success!
kvs> GET b
anna: anna.cpp:89: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
kvs> GET b
0 // responses[0].tuples(0).lattice_type()
1 // LatticeType::LWW
anna: anna.cpp:90: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
```

**Comment by authwork** [comment]
**Issue 3:**

I then have a try on a two-nodes cluster, 
On each node, we run a route, a serve and a client.

On node ```10.1.2.66```:
```
monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring:
      - 127.0.0.1
  ip: 10.1.2.66
user:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
      - 10.1.2.67
  ip: 10.1.2.66
server:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
      - 10.1.2.67
  seed_ip: 10.1.2.66
  public_ip: 10.1.2.66
  private_ip: 10.4.2.2
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
ebs: ./
capacities: # in GB
  memory-cap: 1
  ebs-cap: 0
threads:
  memory: 1
  ebs: 1
  routing: 1
  benchmark: 1
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1
```
On node ```10.1.2.67```:
```
monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring:
      - 127.0.0.1
  ip: 10.1.2.67
user:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
      - 10.1.2.67
  ip: 10.1.2.67
server:
  monitoring:
      - 127.0.0.1
  routing:
      - 10.1.2.66
      - 10.1.2.67
  seed_ip: 10.1.2.66
  public_ip: 10.1.2.67
  private_ip: 10.4.2.3
  mgmt_ip: "NULL"
policy:
  elasticity: false
  selective-rep: false
  tiering: false
ebs: ./
capacities: # in GB
  memory-cap: 1
  ebs-cap: 0
threads:
  memory: 1
  ebs: 1
  routing: 1
  benchmark: 1
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1
```

Output of node ```10.1.2.66```:
```
kvs> PUT a 1.3
Success!
kvs> GET a
1.3
kvs> PUT b 4.5
Success!
kvs> GET b
anna: anna.cpp:87: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
xyao@sr002:/localfs/xyao/addl/apps/anna$ ./anna /localfs/xyao/addl/store/anna/conf/anna-config.yml
kvs> PUT c 2.4
Success!
kvs> PUT d 3.5
Success!
kvs> PUT a 3.678
Success!
kvs> GET e
2.3
kvs> PUT a 1.3
Success!
kvs> GET a
4.5
```
Output of node ```10.1.2.67```:
```
kvs> GET a
0
1
anna: anna.cpp:90: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
xyao@sr001:/localfs/xyao/addl/apps/anna$ ./anna /localfs/xyao/addl/store/anna/conf/anna-config.yml
kvs> GET a
0
1
anna: anna.cpp:90: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
kvs> GET c
1
1
2.4
kvs> GET d
1
1
3.5
kvs> GET b
1
1
4.5
kvs> GET a
0
1
anna: anna.cpp:90: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
kvs> PUT a 4.5
Success!
kvs> GET a
0
1
anna: anna.cpp:90: void handle_request(KvsClientInterface*, string): Assertion `responses[0].tuples(0).lattice_type() == LatticeType::LWW' failed.
Aborted
```
1. Both clients can write all key-value pairs, but they cannot read all of them.
For example, client 1 can read Key a, client 2 cannot read Key b
2. When client 1 updates Key a, the operation latency is very short, while client 2 needs much longer latency to update Key a.
